@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZW1haWwiOiJyYWZhZWxzaWx2YTkyNDBAaG90bWFpbC5jb20iLCJleHAiOjE3MjcwNTg5MjJ9.FC_AKq0qgwPXUVOg9XFxxorj92zC4DcPPd33Ja1M2_4
@url=localhost:80



### Registro
POST http://{{url}}/signup
Content-Type: application/json

{"name":"Fulano","email":"rafaelsilva9241@hotmail.com","password":"123456"}



### Login
POST http://{{url}}/login
Content-Type: application/json

{"email":"rafaelsilva9240@hotmail.com","password":"123456"}



### Confirmar codigo
POST http://{{url}}/confirmate-code
Content-Type: application/json

{"email":"rafaelsilva9240@hotmail.com","code":"123321"}


###

GET http://{{url}}/
Content-Type: application/json


### TAREFAS


### Buscar Tarefas
GET http://{{url}}/task
authorization: Bearer {{token}}
Content-Type: application/json


### Criar Tarefa
POST http://{{url}}/task
Authorization: Bearer {{token}}
Content-Type: application/json

{"description":"Alguma tarefa legal"}



### Atualizar Tarefa
PUT http://{{url}}/task/1
Authorization: Bearer {{token}}
Content-Type: application/json

{"description":"Tarefa legal alterada","done":true}


### Excluir Tarefa
DELETE http://{{url}}/task/1
Authorization: Bearer {{token}}
Content-Type: application/json

{"description":"Outra coisa legal"}
